apiVersion: v1
kind: Endpoints
metadata:
  name: my-endpoints-service
subsets:
  - addresses:
      - ip: 77.68.88.76 # IIS
      - ip: 10.244.0.19 # Apache
      - ip: 10.244.0.18 # Nginx
    ports:
      - port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-endpoints-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
